version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '00:00'
      timezone: America/Chicago
    assignees:
      - Suzuko-Nakajima
    open-pull-requests-limit: 6
    reviewers:
      - Suzuko-Nakajima
